[package]
name = "sandbox"
version = "0.1.0"
authors = ["Eric Trombly <etrombly@yahoo.com>"]
description = "Etch-a-sketch in sand"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/etrombly/sandbox"

[dependencies]
stm32f103xx = "0.10.0"
cortex-m = "0.5.7"
cortex-m-rtfm = "0.3.4"
nb = "0.1.1"
m = "0.1.1"
panic-abort = "0.3.1"

[dependencies.byteorder]
default-features = false
version = "1.2.7"

[dependencies.cobs]
default-features = false
version = "0.1.3"

[dependencies.gcode]
git = "https://github.com/Michael-F-Bryan/gcode-rs"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.stm32f103xx-hal]
git = "https://github.com/japaric/stm32f103xx-hal"

[dependencies.stepper-driver]
git = "https://github.com/etrombly/stepper-driver"

[dev-dependencies]
cortex-m-semihosting = "0.3.1"
cortex-m-rtfm = "0.3.4"
m = "0.1.1"
cortex-m-rt = "0.6.5"

[dev-dependencies.byteorder]
default-features = false
version = "1.2.7"

[dev-dependencies.cobs]
default-features = false
version = "0.1.3"

[dev-dependencies.crc16]
default-features = false
version = "0.4.0"

[dev-dependencies.either]
default-features = false
version = "1.5.0"

[dev-dependencies.stm32f103xx]
features = ["rt"]
version = "0.10.0"

[features]
doc = []
rt = ["stm32f103xx/rt"]

[profile.dev]
incremental = false
codegen-units = 1
lto = true
opt-level = "z" 

[profile.release]
debug = true
lto = true
codegen-units = 1
