[package]
name = "sandbox"
version = "0.2.0"
authors = ["Eric Trombly <etrombly@yahoo.com>"]
description = "Etch-a-sketch in sand"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/etrombly/sandbox"
edition = "2018"

[dependencies]
cortex-m = "0.5.8"
nb = "0.1.1"
cortex-m-semihosting = "0.3.2"
cortex-m-rt = "0.6.8"
libm = "0.1.2"
panic-abort = "0.3.1"
numtoa = "0.2.3"
panic-semihosting = "0.5.1"
panic-itm = "0.4.0"

[dependencies.stm32f1]
version = "0.6.0"
features = ["stm32f103", "rt"]

[dependencies.stm32f1xx-hal]
version = "0.2.1"
features = ["stm32f103", "rt"]

[dependencies.cortex-m-rtfm]
version = "0.4.2"
features = ["nightly"]

[dependencies.byteorder]
default-features = false
version = "1.3.1"

[dependencies.cobs]
default-features = false
version = "0.1.4"

[dependencies.gcode]
git = "https://github.com/Michael-F-Bryan/gcode-rs"

[dependencies.stepper-driver]
git = "https://github.com/etrombly/stepper-driver"

[profile.release]
debug = true
lto = true
codegen-units = 1
opt-level = "z"
