[package]
name = "sandbox"
version = "0.2.0"
authors = ["Eric Trombly <etrombly@yahoo.com>"]
description = "Etch-a-sketch in sand"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/etrombly/sandbox"
edition = "2018"

[dependencies]
cortex-m = "0.5.8"
nb = "0.1.1"
cortex-m-rtfm = "0.4.0"
panic-semihosting = "0.5.1"
cortex-m-semihosting = "0.3.2"
cortex-m-rt = "0.6.7"
libm = "0.1.2"

[dependencies.stm32f103xx]
features = ["rt"]
version = "0.11.0"

[dependencies.byteorder]
default-features = false
version = "1.2.7"

[dependencies.cobs]
default-features = false
version = "0.1.3"

[dependencies.gcode]
git = "https://github.com/Michael-F-Bryan/gcode-rs"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.stm32f103xx-hal]
git = "https://github.com/japaric/stm32f103xx-hal"

[dependencies.stepper-driver]
git = "https://github.com/etrombly/stepper-driver"

[dev-dependencies]
cortex-m-semihosting = "0.3.2"
cortex-m-rt = "0.6.7"

[profile.dev]
incremental = false
codegen-units = 1
lto = true
opt-level = "z" 

[profile.release]
debug = true
lto = true
codegen-units = 1
